using System.Collections.Generic;

namespace AVAVLib
{
	/// <summary>
	/// Addresse hat ähnlich zur Person eine eigene Identität, denn bei
	/// Korrekturen sollen alle Verwendungen einer Addresse korrigiert werden.
	///
	/// Die verschiedenen Änderungsstände einer Addresse bzw. deren Attribute
	/// liegen jeweils in AddressVersions
	/// </summary>
	public partial class Address
	{
		/// <summary>
		/// Generated by Framework/DB for reference use Adid
		/// </summary>
		public int AddressId { get; set; }
		/// <summary>
		/// Kann zur Serialisierung verwendet werden
		/// </summary>
		public string Adid { get; set; }
		/// <summary>
		/// Versionen der Addresse, Änderungsstände
		/// </summary>
		private ICollection<AddressVersion> AddressVersions { get; set; } 
			= new List<AddressVersion>();
	}
}