using System;

namespace AVAVLib
{
	/// <summary>
	/// Version einer Addresse
	/// </summary>
	public partial class AddressVersion
	{
		/// <summary>
		/// Generated by Framework/DB for reference use Address.Adid
		/// </summary>
		public int AddressVersionId { get; set; }
		/// <summary>
		/// Systemzeitstempel, wir verwendet um den jüngsten Stand als
		/// aktuellen Stand zu identifizieren.
		/// </summary>
		public DateTime TimeStamp { get; set; } = DateTime.Now;
		/// <summary>
		/// Zeigt an, ob die Adresse gültig oder schwebend ist.
		/// Ist die Adresse vom Mitglied eingegeben, aber nicht vom
		/// Schriftwart übernommen, bleigt sie schwebend.
		/// </summary>
		public bool Valid { get; set; } = false;
		/// <summary>
		/// Adresse zu der diese Version gehört.
		/// </summary>
		public Address Address { get; set; }
		/// <summary>
		/// Name der Adresse, da Arbeitgeber auch nur Adressen sind, ist dieses Feld
		/// für den Firmennamen vorgesehen.
		/// </summary>
		public String Name { get; set; }

		/// <summary>
		/// Änderungsbeschreibung für genau diese Änderung. (Jede Änderung ist ein Datensatz.)
		/// </summary>
		public ChangeHandle ChangeHandle { get; set; }
		/// <summary>
		/// Können meine Bundesgeschwister die Telefonummer zu dieser Addresse sehen?
		/// </summary>
		public bool IsLandLineVisible { get; set; }
		/// <summary>
		/// Festnetztelefon zu dieser Adresse
		/// </summary>
		public String LandLine { get; set; }
		/// <summary>
		/// Können meine Bundesgeschwister die Faxnummer zu dieser Addresse sehen?
		/// </summary>
		public bool IsFaxVisible { get; set; }
		/// <summary>
		/// Faxnummer zu dieser Adresse
		/// </summary>
		public String Fax { get; set; }
		/// <summary>
		/// Straße
		/// </summary>
		public String Street { get; set; }
		/// <summary>
		/// Postleitzahl
		/// </summary>
		public String PostCode { get; set; }
		/// <summary>
		/// Stadt
		/// </summary>
		public String City { get; set; }
		/// <summary>
		/// Ländercode (Post)
		/// </summary>
		public String CountryCode { get; set; }
	}
}